# Generated by Django 3.0.6 on 2020-05-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_ate',
            new_name='created_at',
        ),
    ]
